import { Box, styled } from "@mui/material";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import Head from "next/head";

const ContentStyled = styled("main")(({ theme }) => ({
  flex: 1,
  background: theme.palette.background.default,
}));

const containerStyle = {
  display: "flex",
  flexDirection: "column",
  minHeight: "100vh",
};

function MainLayout({ children }) {
  return (
    <Box sx={containerStyle}>
      <Navbar />
      <Head>
        <title>Khaled Shouqal Fighter Official</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentStyled>{children}</ContentStyled>
      <Footer />
    </Box>
  );
}

export default MainLayout;
